language: node_js
node_js:
- node
script:
- npm run test
- npm run build
- npm run lint
- npm run docgen
before_deploy:
- cd dist/ng-utils
deploy:
  - provider: script
    skip_cleanup: true
    script:
      - npx semantic-release
    on:
      branch: master
  - provider: pages
    local_dir: dist/doc
    skip_cleanup: true
    github_token: $GH_TOKEN
    on:
      branch: master
