language: node_js
node_js:
- node
script:
- npm run test
- npm run build
before_deploy:
- cd dist/ng-utils
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
  on:
    branch: master
